### ISSUE TITLE
我在windows 下编译成功，貌似不能正常通信

### ISSUE THREAD

**Issue by wangqiangcc** [ccsexyz/kcptun-asio#1]
我在windows 下编译成功，貌似不能正常通信，请问这个测试过了吗？另外我对这个挺感兴趣，是否可以加入这个项目？

**Comment by ccsexyz** [comment]
在mac和linux下都试过是没问题的。感兴趣的话可以fork然后提pr，其实我比较推荐直接使用go版本的，编译部署之类的都比较方便。

**Comment by wangqiangcc** [comment]
可以加一个你的QQ吗，可以交流一下。

**Comment by wangqiangcc** [comment]
我的测试环境：
TCP Server ip地址 192.168.11.194 端口 1188 运行在A PC上
TCP Client  ip地址 192.168.11.193 运行在 B PC 上

运行流程：
A PC 上运行 TCP Server 再后再运行 kcptun_server.exe -c "server-config.json"
B  PC 上运行 kcptun_client.exe -c "client-config.json" 再运行 TCPClient

TCP Client ->(127.0.0.1:1188)->kcptun_client -> kcptun_server(29900) ->TCP Server

配置文件：
服务端
server-config.json
`{
    "listen": ":29900",
    "target": "127.0.0.1:1188",
    "key": "test",
    "crypt": "salsa20",
    "mode": "fast2",
    "mtu": 1350,
    "sndwnd": 1024,
    "rcvwnd": 1024,
    "datashard": 70,
    "parityshard": 30,
    "dscp": 46,
    "nocomp": false,
    "acknodelay": false,
    "nodelay": 0,
    "interval": 40,
    "resend": 0,
    "nc": 0,
    "sockbuf": 4194304,
    "keepalive": 10
}`

客户端
client-config.json
`{
    "localaddr": ":1188",
    "remoteaddr": "192.168.11.194:29900",
    "key": "test",
    "crypt": "salsa20",
    "mode": "fast2",
    "conn": 1,
    "autoexpire": 60,
    "mtu": 1350,
    "sndwnd": 128,
    "rcvwnd": 1024,
    "datashard": 70,
    "parityshard": 30,
    "dscp": 46,
    "nocomp": false,
    "acknodelay": false,
    "nodelay": 0,
    "interval": 40,
    "resend": 0,
    "nc": 0,
    "sockbuf": 4194304,
    "keepalive": 10
}`

**Comment by ccsexyz** [comment]
能提供输出日志吗？以及最好抓下包看看结果

**Comment by wangqiangcc** [comment]
我fork了一个，然后修改了提交了，你看看那里有问题，导致不能正常通信，也可以合并过来
https://github.com/dnybz/kcptun-asio

**Comment by ccsexyz** [comment]
感觉改动太大了，而且我最近可能没时间处理这个问题，你先抓抓包查查问题吧。

**Comment by wangqiangcc** [comment]
好的，谢谢

**Comment by wangqiangcc** [comment]
我把本地IP　的127.0.0.1 改成 指定本机网卡的IP 问题就解决了。
