### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by majorcheng** [ccsexyz/kcptun-asio#4]
make[3]: *** No rule to make target `gflags/libgflags_nothreads.a', needed by `kcptun_client'.  Stop.
make[2]: *** [CMakeFiles/kcptun_client.dir/all] Error 2
make[1]: *** [CMakeFiles/kcptun_client.dir/rule] Error 2

**Comment by ccsexyz** [comment]
编译命令是什么？操作系统和编译器版本是多少？以及更详细的错误信息？

**Comment by majorcheng** [comment]
估计是一开始cmake版本太低，编译中间升级了一下导致，重新完全删除后重新git clone编译成功了：）
